// Email validation utilities for preventing trial abuse

// List of known disposable email domains
const DISPOSABLE_EMAIL_DOMAINS = [
  // Popular disposable email services
  '10minutemail.com', '10minutemail.net', '10minmail.com',
  'tempmail.com', 'temp-mail.org', 'tempail.com',
  'guerrillamail.com', 'guerrillamail.org', 'guerrillamail.net',
  'mailinator.com', 'mailinator.net', 'mailinator2.com',
  'throwaway.email', 'throwawaymail.com',
  'fakeinbox.com', 'fakemailgenerator.com',
  'getnada.com', 'nada.email',
  'mohmal.com', 'mohmal.im',
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'maildrop.cc', 'mailnesia.com',
  'dispostable.com', 'discard.email',
  'sharklasers.com', 'guerrillamailblock.com',
  'spam4.me', 'spamgourmet.com',
  'trashmail.com', 'trashmail.net', 'trashmail.org',
  'mailexpire.com', 'tempinbox.com',
  'emailondeck.com', 'anonymbox.com',
  'mintemail.com', 'burnermail.io',
  'temp.email', 'tempmailo.com',
  'emailfake.com', 'crazymailing.com',
  'mailcatch.com', 'mailsac.com',
  'inboxalias.com', 'incognitomail.org',
  'dropmail.me', 'harakirimail.com',
  'jetable.org', 'kasmail.com',
  'mytemp.email', 'nowmymail.com',
  'spambox.us', 'tempmailaddress.com',
  'wegwerfmail.de', 'wegwerfmail.net',
  'zoemail.org', '33mail.com',
  'amilegit.com', 'anonymmail.net',
  'binkmail.com', 'bobmail.info',
  'burnthespam.info', 'byom.de',
  'chammy.info', 'courrieltemporaire.com',
  'dead.email', 'despam.it',
  'devnullmail.com', 'einrot.com',
  'emailisvalid.com', 'emz.net',
  'enterto.com', 'ephemail.net',
  'etranquil.com', 'eyepaste.com',
  'fastacura.com', 'filzmail.com',
  'freemail.ms', 'garliclife.com',
  'geronra.com', 'getonemail.com',
  'gishpuppy.com', 'goemailgo.com',
  'great-host.in', 'greensloth.com',
  'haltospam.com', 'hotpop.com',
  'ieatspam.eu', 'ieatspam.info',
  'imgof.com', 'inboxclean.com',
  'inboxclean.org', 'instant-mail.de',
  'ipoo.org', 'irish2me.com',
  'jetable.com', 'jnxjn.com',
  'junk.email', 'kasmail.net',
  'klassmaster.com', 'klassmaster.net',
  'klzlv.com', 'kulturbetrieb.info',
  'kurzepost.de', 'lawlita.com',
  'letthemeatspam.com', 'lhsdv.com',
  'lifebyfood.com', 'link2mail.net',
  'litedrop.com', 'lol.ovpn.to',
  'lookugly.com', 'lopl.co.cc',
  'lortemail.dk', 'lovemeleaveme.com',
  'lr78.com', 'maboard.com',
  'mail-hierarchie.net', 'mail.by',
  'mail.htl22.at', 'mail.mezimages.net',
  'mail.zp.ua', 'mail2rss.org',
  'mailbidon.com', 'mailblocks.com',
  'mailcatch.com', 'mailde.de',
  'mailde.info', 'maildx.com',
  'mailed.ro', 'mailexpire.com',
  'mailfa.tk', 'mailfreeonline.com',
  'mailin8r.com', 'mailinater.com',
  'mailincubator.com', 'mailismagic.com',
  'mailjunk.cf', 'mailjunk.ga',
  'mailjunk.gq', 'mailjunk.ml',
  'mailjunk.tk', 'mailmate.com',
  'mailme.gq', 'mailme.ir',
  'mailme.lv', 'mailna.biz',
  'mailna.co', 'mailna.in',
  'mailna.me', 'mailnator.com',
  'mailnesia.com', 'mailnull.com',
  'mailorg.org', 'mailpick.biz',
  'mailproxsy.com', 'mailquack.com',
  'mailrock.biz', 'mailsac.com',
  'mailseal.de', 'mailsiphon.com',
  'mailslapping.com', 'mailslite.com',
  'mailtemp.info', 'mailtothis.com',
  'mailzilla.com', 'mailzilla.org',
  'makemetheking.com', 'manifestgenerator.com',
  'manybrain.com', 'mbx.cc',
  'mega.zik.dj', 'meinspamschutz.de',
  'meltmail.com', 'messagebeamer.de',
  'mezimages.net', 'mierdamail.com',
  'migmail.pl', 'migumail.com',
  'mintemail.com', 'moakt.com',
  'mobi.web.id', 'mobileninja.co.uk',
  'moburl.com', 'moncourrier.fr.nf',
  'monemail.fr.nf', 'monmail.fr.nf',
  'monumentmail.com', 'ms9.mailslite.com',
  'msb.minsmail.com', 'mt2009.com',
  'mt2014.com', 'myalias.pw',
  'mycleaninbox.net', 'myemailboxy.com',
  'mymail-in.net', 'mymailoasis.com',
  'mynetstore.de', 'mypacks.net',
  'mypartyclip.de', 'myphantomemail.com',
  'myspaceinc.com', 'myspaceinc.net',
  'myspacepimpedup.com', 'mytrashmail.com',
  'neomailbox.com', 'nepwk.com',
  'nervmich.net', 'nervtmansen.de',
  'netmails.com', 'netmails.net',
  'netzidiot.de', 'neverbox.com',
  'nice-4u.com', 'nincsmail.hu',
  'nmail.cf', 'nobulk.com',
  'noclickemail.com', 'nogmailspam.info',
  'nomail.xl.cx', 'nomail2me.com',
  'nomorespamemails.com', 'nospam.ze.tc',
  'nospam4.us', 'nospamfor.us',
  'nospammail.net', 'nospamthanks.info',
  'notmailinator.com', 'nowmymail.com',
  'nurfuerspam.de', 'nus.edu.sg',
  'nwldx.com', 'objectmail.com',
  'obobbo.com', 'odnorazovoe.ru',
  'ohaaa.de', 'omail.pro',
  'oneoffemail.com', 'onewaymail.com',
  'onlatedotcom.info', 'online.ms',
  'oopi.org', 'opayq.com',
  'ordinaryamerican.net', 'otherinbox.com',
  'ourklips.com', 'outlawspam.com',
  'ovpn.to', 'owlpic.com',
  'pancakemail.com', 'pjjkp.com',
  'plexolan.de', 'poczta.onet.pl',
  'politikerclub.de', 'poofy.org',
  'pookmail.com', 'privacy.net',
  'privy-mail.com', 'privymail.de',
  'proxymail.eu', 'prtnx.com',
  'punkass.com', 'putthisinyourspamdatabase.com',
  'qq.com', 'quickinbox.com',
  'quickmail.nl', 'rcpt.at',
  'reallymymail.com', 'realtyalerts.ca',
  'recode.me', 'recursor.net',
  'recyclemail.dk', 'regbypass.com',
  'regbypass.comsafe-mail.net', 'rejectmail.com',
  'reliable-mail.com', 'remail.cf',
  'remail.ga', 'rhyta.com',
  'rklips.com', 'rmqkr.net',
  'royal.net', 'rppkn.com',
  'rtrtr.com', 's0ny.net',
  'safe-mail.net', 'safersignup.de',
  'safetymail.info', 'safetypost.de',
  'sandelf.de', 'saynotospams.com',
  'schafmail.de', 'schrott-email.de',
  'secretemail.de', 'secure-mail.biz',
  'selfdestructingmail.com', 'sendspamhere.com',
  'senseless-entertainment.com', 'server.ms.selfip.net',
  'sharedmailbox.org', 'sharklasers.com',
  'shieldedmail.com', 'shiftmail.com',
  'shitmail.me', 'shortmail.net',
  'shut.name', 'shut.ws',
  'sibmail.com', 'sinnlos-mail.de',
  'siteposter.net', 'skeefmail.com',
  'slaskpost.se', 'slave-auctions.net',
  'slopsbox.com', 'slowslow.de',
  'smashmail.de', 'smellfear.com',
  'snakemail.com', 'sneakemail.com',
  'sneakmail.de', 'snkmail.com',
  'sofimail.com', 'sofort-mail.de',
  'sogetthis.com', 'soodonims.com',
  'spam.la', 'spam.su',
  'spam4.me', 'spamavert.com',
  'spambob.com', 'spambob.net',
  'spambob.org', 'spambog.com',
  'spambog.de', 'spambog.net',
  'spambog.ru', 'spambox.info',
  'spambox.irishspringrealty.com', 'spambox.us',
  'spamcannon.com', 'spamcannon.net',
  'spamcero.com', 'spamcon.org',
  'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org',
  'spamday.com', 'spamex.com',
  'spamfighter.cf', 'spamfighter.ga',
  'spamfighter.gq', 'spamfighter.ml',
  'spamfighter.tk', 'spamfree.eu',
  'spamfree24.com', 'spamfree24.de',
  'spamfree24.eu', 'spamfree24.info',
  'spamfree24.net', 'spamfree24.org',
  'spamgoes.in', 'spamgourmet.com',
  'spamgourmet.net', 'spamgourmet.org',
  'spamherelots.com', 'spamhereplease.com',
  'spamhole.com', 'spamify.com',
  'spaminator.de', 'spamkill.info',
  'spaml.com', 'spaml.de',
  'spammotel.com', 'spamobox.com',
  'spamoff.de', 'spamsalad.in',
  'spamslicer.com', 'spamspot.com',
  'spamstack.net', 'spamthis.co.uk',
  'spamthisplease.com', 'spamtrail.com',
  'spamtroll.net', 'speed.1s.fr',
  'spoofmail.de', 'squizzy.de',
  'ssoia.com', 'startkeys.com',
  'stinkefinger.net', 'stop-my-spam.cf',
  'stop-my-spam.com', 'stop-my-spam.ga',
  'stop-my-spam.ml', 'stop-my-spam.tk',
  'streetwisemail.com', 'stuffmail.de',
  'super-auswahl.de', 'supergreatmail.com',
  'supermailer.jp', 'superrito.com',
  'superstachel.de', 'suremail.info',
  'svk.jp', 'sweetxxx.de',
  'tagyourself.com', 'talkinator.com',
  'tapchicuoihoi.com', 'techemail.com',
  'techgroup.me', 'teewars.org',
  'teleosaurs.xyz', 'teleworm.com',
  'teleworm.us', 'temp-mail.de',
  'temp-mail.ru', 'temp.headstrong.de',
  'tempail.com', 'tempalias.com',
  'tempe-mail.com', 'tempemail.biz',
  'tempemail.co.za', 'tempemail.com',
  'tempemail.net', 'tempinbox.co.uk',
  'tempinbox.com', 'tempmail.co',
  'tempmail.de', 'tempmail.eu',
  'tempmail.it', 'tempmail.net',
  'tempmail.us', 'tempmail2.com',
  'tempmaildemo.com', 'tempmailer.com',
  'tempmailer.de', 'tempomail.fr',
  'temporarily.de', 'temporarioemail.com.br',
  'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com', 'temporaryinbox.com',
  'temporarymailaddress.com', 'tempthe.net',
  'thankyou2010.com', 'thecloudindex.com',
  'thelimestones.com', 'thisisnotmyrealemail.com',
  'throam.com', 'throwawayemailaddress.com',
  'throwawaymail.com', 'tilien.com',
  'tittbit.in', 'tmailinator.com',
  'toiea.com', 'toomail.biz',
  'topranklist.de', 'tradermail.info',
  'trash-amil.com', 'trash-mail.at',
  'trash-mail.com', 'trash-mail.de',
  'trash-mail.ga', 'trash-mail.gq',
  'trash-mail.ml', 'trash-mail.tk',
  'trash2009.com', 'trash2010.com',
  'trash2011.com', 'trashbox.eu',
  'trashdevil.com', 'trashdevil.de',
  'trashemail.de', 'trashmail.at',
  'trashmail.com', 'trashmail.de',
  'trashmail.me', 'trashmail.net',
  'trashmail.org', 'trashmail.ws',
  'trashmailer.com', 'trashymail.com',
  'trashymail.net', 'trbvm.com',
  'trickmail.net', 'trillianpro.com',
  'tryalert.com', 'turual.com',
  'twinmail.de', 'tyldd.com',
  'uggsrock.com', 'umail.net',
  'upliftnow.com', 'uplipht.com',
  'uroid.com', 'us.af',
  'valemail.net', 'venompen.com',
  'veryrealemail.com', 'viditag.com',
  'viewcastmedia.com', 'viewcastmedia.net',
  'viewcastmedia.org', 'viralplays.com',
  'vkcode.ru', 'vomoto.com',
  'vubby.com', 'wahr.com',
  'walkmail.net', 'webemail.me',
  'webm4il.info', 'webuser.in',
  'wee.my', 'weg-werf-email.de',
  'wegwerf-email-addressen.de', 'wegwerf-emails.de',
  'wegwerfadresse.de', 'wegwerfemail.com',
  'wegwerfemail.de', 'wegwerfmail.de',
  'wegwerfmail.info', 'wegwerfmail.net',
  'wegwerfmail.org', 'wetrainbayarea.com',
  'wetrainbayarea.org', 'wh4f.org',
  'whatiaas.com', 'whatpaas.com',
  'whopy.com', 'whtjddn.33mail.com',
  'whyspam.me', 'wilemail.com',
  'willhackforfood.biz', 'willselfdestruct.com',
  'winemaven.info', 'wolfsmail.tk',
  'wollan.info', 'worldspace.link',
  'wraptr.com', 'wronghead.com',
  'wuzup.net', 'wuzupmail.net',
  'wwwnew.eu', 'xagloo.co',
  'xagloo.com', 'xemaps.com',
  'xents.com', 'xmaily.com',
  'xoxy.net', 'yapped.net',
  'yep.it', 'yogamaven.com',
  'yopmail.com', 'yopmail.fr',
  'yopmail.net', 'yourdomain.com',
  'ypmail.webarnak.fr.eu.org', 'yuurok.com',
  'z1p.biz', 'za.com',
  'zehnminuten.de', 'zehnminutenmail.de',
  'zetmail.com', 'zippymail.info',
  'zoaxe.com', 'zoemail.com',
  'zoemail.net', 'zoemail.org',
  'zomg.info', 'zxcv.com',
  'zxcvbnm.com', 'zzz.com'
];

/**
 * Check if an email domain is a known disposable email service
 * @param {string} email - The email address to check
 * @returns {boolean} - True if the email is from a disposable domain
 */
export function isDisposableEmail(email) {
  if (!email || typeof email !== 'string') return true;
  
  const domain = email.toLowerCase().split('@')[1];
  if (!domain) return true;
  
  return DISPOSABLE_EMAIL_DOMAINS.includes(domain);
}

/**
 * Validate email format
 * @param {string} email - The email address to validate
 * @returns {boolean} - True if the email format is valid
 */
export function isValidEmailFormat(email) {
  if (!email || typeof email !== 'string') return false;
  
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

/**
 * Full email validation for trial registration
 * @param {string} email - The email address to validate
 * @returns {{ valid: boolean, reason?: string }} - Validation result
 */
export function validateEmailForTrial(email) {
  if (!email) {
    return { valid: false, reason: 'EMAIL_REQUIRED' };
  }
  
  if (!isValidEmailFormat(email)) {
    return { valid: false, reason: 'INVALID_FORMAT' };
  }
  
  if (isDisposableEmail(email)) {
    return { valid: false, reason: 'DISPOSABLE_EMAIL' };
  }
  
  return { valid: true };
}

export { DISPOSABLE_EMAIL_DOMAINS };

